### PR TITLE
Set tweet to be generated into a tweet card by passing in the tweet ID

### PR DESCRIPTION
**Pull request by abuuzayr**
With reference to Issue #1 : now a tweet card with be automatically generated as opposed to being hardcoded by passing in the tweet ID.

### CODE REVIEW

**Comment by jawache** [comment]
Hi @abuuzayr, thanks for this! I tried checking it out however I couldn't get a tweet to load even if I hardcoded a tweet id as the "latestTweetId" - would you mind double checking and perhaps checkin  a version which has a hardcoded tweetId?

ALSO, another PR has been merged which has caused this one to have merge issues :( so first do a pull from the upstream so you get those changed in your branch and then use that code to push again, see this for instructions: https://help.github.com/articles/merging-an-upstream-repository-into-your-fork/

**Comment by abuuzayr** [comment]
Hi @jawache thanks for reviewing it! 

It was working perfectly before I submitted the PR. But you're right, now it doesn't and I am pretty stumped. Let me retrace my steps and submit a revision.

**Comment by abuuzayr** [comment]
Hi @jawache, I fixed the issue and it should work on your end now. 

screen shot 2017-12-23 at 11 44 45 am

Please let me know if it doesn't, and thank you again for your time!

**Comment by jawache** [comment]
Thanks @abuuzayr ! I can confirm it's working now great work 👍

**Pull request merged**
